<?php 
/*42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58*/
	$GongNengArray = array(
				array (
						'id' =>42, 
						'pid' => 41,
						'name' => '微餐饮',
						'url' => "{weixin::U('Dining/ComBranches',array('token'=>$token,'dining'=>1))}",
						'info' => '',
				  ),
				   array (
						'id' =>43, 
						'pid' => 41,
						'name' => '微婚庆',
						'url' => "{weixin::U('Hunqing/index',array('token'=>$token))}",
						'info' => '',
				  ),
				   array (
						'id' =>44, 
						'pid' => 41,
						'name' =>'微喜帖',
						'url' => "{weixin::U('Wedding/index',array('token'=>$token))}",
						'info' => '',
				  ),
				   array (
						'id' =>45, 
						'pid' => 41,
						'name' => '微汽车',
						'url' => "{weixin::U('Car/index',array('token'=>$token))}",
						'info' => '',
				  ),
				   array (
						'id' =>46, 
						'pid' => 41,
						'name' => '微医疗',
						'url' => "{weixin::U('Yiliao/index',array('token'=>$token))}",
						'info' => '',
				  ),
				   array (
						'id' =>47, 
						'pid' => 41,
						'name' => '微酒店',
						'url' => "{weixin::U('Jiudian/index',array('token'=>$token))}",
						'info' => '',
				  ),
				   array (
						'id' =>48, 
						'pid' => 41,
						'name' => '楼盘房产',
						'url' => "{weixin::U('Estate/index',array('token'=>$token))}",
						'info' => '',
				  ),
				   array (
						'id' =>49, 
						'pid' => 41,
						'name' => '微美容',
						'url' => "{weixin::U('Meirong/index',array('token'=>$token))}",
						'info' => '',
				  ),
				   array (
						'id' =>50, 
						'pid' => 41,
						'name' => '微旅游',
						'url' => "{weixin::U('Lvyou/index',array('token'=>$token))}",
						'info' => '',
				  ),
				   array (
						'id' =>51, 
						'pid' => 41,
						'name' => '微健身',
						'url' => "{weixin::U('Jianshen/index',array('token'=>$token))}",
						'info' => '',
				  ),
				   array (
						'id' =>52, 
						'pid' => 41,
						'name' => '微政务',
						'url' => "{weixin::U('Zhengwu/index',array('token'=>$token))}",
						'info' => '',
				  ),
				   array (
						'id' =>53, 
						'pid' => 41,
						'name' => '微物业',
						'url' => "{weixin::U('Wuye/index',array('token'=>$token))}",
						'info' => '',
				  ),
				   array (
						'id' =>54, 
						'pid' => 41,
						'name' => '微KTV',
						'url' => "{weixin::U('Ktv/index',array('token'=>$token))}",
						'info' => '',
				  ),
				   array (
						'id' =>55, 
						'pid' => 41,
						'name' => '微酒吧',
						'url' => "{weixin::U('Jiuba/index',array('token'=>$token))}",
						'info' => '',
				  ),
				   array (
						'id' =>56, 
						'pid' => 41,
						'name' => '微装修',
						'url' => "{weixin::U('Zhuangxiu/index',array('token'=>$token))}",
						'info' => '',
				  ),
				   array (
						'id' =>57, 
						'pid' => 41,
						'name' => '微教育',
						'url' => "{weixin::U('Jiaoyu/index',array('token'=>$token))}",
						'info' => '',
				  ),
				   array (
						'id' =>58, 
						'pid' => 41,
						'name' => '微花店',
						'url' => "{weixin::U('Huadian/index',array('token'=>$token))}",
						'info' => '',
				  )
				
		);
